version: "3.9"
networks:
    webproject-dev:
        driver: bridge
services: 
    app:
        container_name: mywebproject-cont
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        networks:
            - webproject-dev
        depends_on:
            - mysql-db
    mysql-db:
        container_name: mysql-container
        build:
            context: .
            dockerfile: Dockerfile
        image: mysql
        environment:
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: itransition_task4
        ports:
          - "3306:3306"
        networks:
          - webproject-dev        
        volumes:
          - mysql-data:/var/lib.mysql/data
volumes:
    mysql-data:
            