services:
  - name: mysql
    type: private
    env:
      MYSQL_DATABASE: my_database
      MYSQL_USER: mysql
      MYSQL_PASSWORD: your_secure_password
      MYSQL_ROOT_PASSWORD: your_secure_root_password
    disk:
      name: mysql
      mountPath: /var/lib/mysql
      sizeGB: 1
  - name: phpmyadmin
    type: web
    env:
      PMA_HOST: mysql:3306
      PMA_USER: mysql
      PMA_PASSWORD: your_secure_password
